"""final

Revision ID: 17f0c918c847
Revises: 3a2bf809a575
Create Date: 2024-12-22 17:50:51.288004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17f0c918c847'
down_revision: Union[str, None] = '3a2bf809a575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_address_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'address', ['address_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('product_image_id_fkey', 'product', type_='foreignkey')
    op.drop_constraint('product_supplier_id_fkey', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'images', ['image_id'], ['id'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'product', 'supplier', ['supplier_id'], ['id'], source_schema='public', referent_schema='public')
    op.drop_constraint('supplier_address_id_fkey', 'supplier', type_='foreignkey')
    op.create_foreign_key(None, 'supplier', 'address', ['address_id'], ['id'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', schema='public', type_='foreignkey')
    op.create_foreign_key('supplier_address_id_fkey', 'supplier', 'address', ['address_id'], ['id'])
    op.drop_constraint(None, 'product', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'product', schema='public', type_='foreignkey')
    op.create_foreign_key('product_supplier_id_fkey', 'product', 'supplier', ['supplier_id'], ['id'])
    op.create_foreign_key('product_image_id_fkey', 'product', 'images', ['image_id'], ['id'])
    op.drop_constraint(None, 'client', schema='public', type_='foreignkey')
    op.create_foreign_key('client_address_id_fkey', 'client', 'address', ['address_id'], ['id'])
    # ### end Alembic commands ###
