"""retern_fk

Revision ID: 6328a2bf833b
Revises: f861ffd929d2
Create Date: 2024-12-22 15:43:42.166784

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6328a2bf833b"
down_revision: Union[str, None] = "f861ffd929d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("client_address_id_fkey", "client", type_="foreignkey")
    op.create_foreign_key(
        None,
        "client",
        "address",
        ["address_id"],
        ["id"],
    )
    op.alter_column("product", "supplier_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        None,
        "product",
        "supplier",
        ["supplier_id"],
        ["id"],
    )
    op.create_foreign_key(
        None,
        "product",
        "images",
        ["image_id"],
        ["id"],
    )
    op.drop_constraint("supplier_address_id_fkey", "supplier", type_="foreignkey")
    op.create_foreign_key(
        None,
        "supplier",
        "address",
        ["address_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "supplier", type_="foreignkey")
    op.create_foreign_key(
        "supplier_address_id_fkey", "supplier", "address", ["address_id"], ["id"]
    )
    op.drop_constraint(None, "product", type_="foreignkey")
    op.drop_constraint(None, "product", type_="foreignkey")
    op.alter_column("product", "supplier_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(None, "client", type_="foreignkey")
    op.create_foreign_key(
        "client_address_id_fkey", "client", "address", ["address_id"], ["id"]
    )
    # ### end Alembic commands ###
