"""nullable_true

Revision ID: 37f64cd6ca03
Revises: 000a5e7c2310
Create Date: 2024-12-22 15:32:48.462837

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37f64cd6ca03"
down_revision: Union[str, None] = "000a5e7c2310"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("client", "address_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("client_address_id_fkey", "client", type_="foreignkey")
    op.create_foreign_key(
        None,
        "client",
        "address",
        ["address_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.alter_column("product", "image_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint("product_supplier_id_fkey", "product", type_="foreignkey")
    op.drop_constraint("product_image_id_fkey", "product", type_="foreignkey")
    op.create_foreign_key(
        None,
        "product",
        "supplier",
        ["supplier_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.create_foreign_key(
        None,
        "product",
        "images",
        ["image_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    op.drop_constraint("supplier_address_id_fkey", "supplier", type_="foreignkey")
    op.create_foreign_key(
        None,
        "supplier",
        "address",
        ["address_id"],
        ["id"],
        source_schema="public",
        referent_schema="public",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "supplier", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "supplier_address_id_fkey", "supplier", "address", ["address_id"], ["id"]
    )
    op.drop_constraint(None, "product", schema="public", type_="foreignkey")
    op.drop_constraint(None, "product", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "product_image_id_fkey", "product", "images", ["image_id"], ["id"]
    )
    op.create_foreign_key(
        "product_supplier_id_fkey", "product", "supplier", ["supplier_id"], ["id"]
    )
    op.alter_column("product", "image_id", existing_type=sa.UUID(), nullable=False)
    op.drop_constraint(None, "client", schema="public", type_="foreignkey")
    op.create_foreign_key(
        "client_address_id_fkey", "client", "address", ["address_id"], ["id"]
    )
    op.alter_column("client", "address_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
