"""delete_fk

Revision ID: f861ffd929d2
Revises: 37f64cd6ca03
Create Date: 2024-12-22 15:42:48.057846

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "f861ffd929d2"
down_revision: Union[str, None] = "37f64cd6ca03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("client_address_id_fkey", "client", type_="foreignkey")
    op.create_foreign_key(
        None,
        "client",
        "address",
        ["address_id"],
        ["id"],
    )
    op.drop_constraint("product_image_id_fkey", "product", type_="foreignkey")
    op.drop_constraint("product_supplier_id_fkey", "product", type_="foreignkey")
    op.drop_constraint("supplier_address_id_fkey", "supplier", type_="foreignkey")
    op.create_foreign_key(
        None,
        "supplier",
        "address",
        ["address_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "supplier", type_="foreignkey")
    op.create_foreign_key(
        "supplier_address_id_fkey", "supplier", "address", ["address_id"], ["id"]
    )
    op.create_foreign_key(
        "product_supplier_id_fkey", "product", "supplier", ["supplier_id"], ["id"]
    )
    op.create_foreign_key(
        "product_image_id_fkey", "product", "images", ["image_id"], ["id"]
    )
    op.drop_constraint(None, "client", type_="foreignkey")
    op.create_foreign_key(
        "client_address_id_fkey", "client", "address", ["address_id"], ["id"]
    )
    # ### end Alembic commands ###
