from repositories.address import AddressRepository
from repositories.client import ClientRepository
from repositories.images import ImagesRepository
from repositories.product import ProductRepository
from repositories.supplier import SupplierRepository
